### ISSUE TITLE
Frontend Cheat sheet resources are not reachable

### ISSUE THREAD

**Issue by JLohani** [jeannienguyen/quick-resources-for-developers#4]
JavaScript Regular Expression shows error 502 Bad Gateway.
Also, the CSS Specificity page is not reachable.

**Comment by jeannienguyen** [comment]
Hey @JLohani, you're right! Do you want to make a PR to remove them?

**Comment by JLohani** [comment]
Sure. I would do some research about the resources and will replace them with working ones.

**Comment by JLohani** [comment]
For regular expression, the current resource is now working so I am not making any changes to that.

After some research, I have found 2 resources for Specificity:
[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)
[CSS-Tricks](https://css-tricks.com/specifics-on-css-specificity/)

I found MDN ones more reliable but I think you should have a look at other alternatives too before I create a PR.

**Comment by jeannienguyen** [comment]
Hey @JLohani, thanks for doing the research!

I like the CSS-Tricks one. Feel free to add that one. I've also found https://polypane.app/css-specificity-calculator/ if you don't mind tossing that in your PR as well.

Thanks!

**Comment by JLohani** [comment]
I have submitted the PR for the Specificity Resource. 
Can you please add the hactoberfest and hacktoberfest-accepted tags so that my PR can be counted in the Event?

Also talking about Specificity Calculator, there's already a resource about that under design resources. But if you want me to replace that with the one above, I would do that as well.

**Comment by jeannienguyen** [comment]
Looks good to me. Thanks, @JLohani! Closing this issue.
